spring:
  application:
    name: voidcatsmarket
  datasource:
    url: jdbc:postgresql://localhost:5432/voidcatsmarket
    username: amaibun
    password: dbpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
feature:
  toggles:
    cosmocats:
      enabled: true
    kittyproducts:
      enabled: false
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
